[theme]

# Primary accent for interactive elements
primaryColor = '#FF4B4B'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1A1A1C'

# Color used for almost all text
textColor = '#17C2EA'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "serif"
font = "serif"

[deprecation]
showPyplotGlobalUse = false